<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>goldenMistake</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="TMPLoader">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\BepInEx\plugins\TMPLoader\TMPLoader.dll</HintPath>
    </Reference>
    <Reference Include="UniTask.TextMeshPro">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UniTask.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\..\..\..\Downloads\Gtag Video Sound Efects\referances\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs maker\" />
  </ItemGroup>

</Project>
